// Edit this file to update SSC event metadata.
// Add new ticketed events to `upcoming`; move hosted events into `past`.
// Past events are grouped automatically by the year in the `date` field.
window.SSC_EVENTS = {
  stats: {
    hostedEvents: 24,
    matchedCouples: 74,
  },
  upcoming: [
    {
      dateLabel: "July 8",
      title: "Speed Dating Dinner",
      venue: "Mala Midtown",
      time: "6:30 PM",
      seats: "32 singles",
      menu: "4-course",
      image: "assets/framer/event-midtown-20260708.png?v=20260612-final",
      imageAlt: "July 8 Dinner and Get Lucky event poster for Mala Project Midtown East 53rd Street",
      ctaLabel: "RSVP on Luma",
      ctaUrl: "https://luma.com/1yinpuet",
    },
    {
      dateLabel: "July 11",
      title: "Speed Dating Brunch",
      venue: "Mala Greenpoint",
      time: "12:30 PM",
      seats: "40 singles",
      menu: "3-course",
      image: "assets/framer/event-greenpoint-20260711.png?v=20260612-final",
      imageAlt: "July 11 Love at First Spice brunch poster for Mala Project Greenpoint",
      ctaLabel: "RSVP on Luma",
      ctaUrl: "https://luma.com/x632vvne",
    },
    {
      dateLabel: "August 15",
      title: "Speed Dating Brunch",
      venue: "Mala Greenpoint",
      time: "12:30 PM",
      seats: "40 singles",
      menu: "3-course",
      image: "assets/framer/event-greenpoint-20260815.png?v=20260625-events",
      imageAlt: "August 15 Love at First Spice brunch poster for Mala Project Greenpoint",
      ctaLabel: "RSVP on Luma",
      ctaUrl: "https://luma.com/3qd2ff20",
    },
    {
      dateLabel: "August 26",
      title: "Speed Dating Dinner",
      venue: "Mala Midtown",
      time: "6:30 PM",
      seats: "32 singles",
      menu: "4-course",
      image: "assets/framer/event-midtown-20260826.png?v=20260625-events",
      imageAlt: "August 26 Dinner and Get Lucky event poster for Mala Project Midtown East 53rd Street",
      ctaLabel: "Coming soon",
      ctaDisabled: true,
    },
    {
      dateLabel: "September 9",
      title: "Speed Dating Dinner",
      venue: "Mala Midtown",
      time: "6:30 PM",
      seats: "32 singles",
      menu: "4-course",
      image: "assets/framer/event-midtown-20260909.png?v=20260625-events",
      imageAlt: "September 9 Dinner and Get Lucky event poster for Mala Project Midtown East 53rd Street",
      ctaLabel: "RSVP on Luma",
      ctaUrl: "https://luma.com/bfwvl8sz",
    },
    {
      dateLabel: "September 19",
      title: "Speed Dating Brunch",
      venue: "Mala Greenpoint",
      time: "12:30 PM",
      seats: "40 singles",
      menu: "3-course",
      image: "assets/framer/event-greenpoint-20260919.png?v=20260625-events",
      imageAlt: "September 19 Love at First Spice brunch poster for Mala Project Greenpoint",
      ctaLabel: "RSVP on Luma",
      ctaUrl: "https://luma.com/x3i69jos",
    },
    {
      dateLabel: "October 7",
      title: "Speed Dating Dinner",
      venue: "Mala Midtown",
      time: "6:30 PM",
      seats: "32 singles",
      menu: "4-course",
      image: "assets/framer/event-midtown-20261007.png?v=20260625-events",
      imageAlt: "October 7 Dinner and Get Lucky event poster for Mala Project Midtown East 53rd Street",
      ctaLabel: "RSVP on Luma",
      ctaUrl: "https://luma.com/h3ccjszq",
    },
    {
      dateLabel: "October 17",
      title: "Speed Dating Brunch",
      venue: "Mala Greenpoint",
      time: "12:30 PM",
      seats: "40 singles",
      menu: "3-course",
      image: "assets/framer/event-greenpoint-20261017.png?v=20260625-events",
      imageAlt: "October 17 Love at First Spice brunch poster for Mala Project Greenpoint",
      ctaLabel: "RSVP on Luma",
      ctaUrl: "https://luma.com/xomycc2b",
    },
  ],
  past: [
    {
      date: "2026-06-13",
      dateLabel: "6/13",
      title: "Speed Dating Brunch @ MáLà Greenpoint",
      stats: "40 Singles, 6 Matches Made",
    },
    {
      date: "2026-06-10",
      dateLabel: "6/10",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 2 Matches Made",
    },
    {
      date: "2026-05-23",
      dateLabel: "5/23",
      title: "Speed Dating Brunch @ MáLà Greenpoint",
      stats: "40 Singles, 4 Matches Made",
    },
    {
      date: "2026-05-05",
      dateLabel: "5/5",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 1 Matches Made",
    },
    {
      date: "2026-04-11",
      dateLabel: "4/11",
      title: "Speed Dating Brunch @ MáLà Greenpoint",
      stats: "40 Singles, 2 Matches Made",
    },
    {
      date: "2026-04-07",
      dateLabel: "4/7",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 3 Matches Made",
    },
    {
      date: "2026-03-18",
      dateLabel: "3/18",
      title: "Speed Dating Brunch @ MáLà Greenpoint",
      stats: "40 Singles, 3 Matches Made",
    },
    {
      date: "2026-03-11",
      dateLabel: "3/11",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 2 Matches Made",
    },
    {
      date: "2026-03-02",
      dateLabel: "3/2",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 4 Matches Made",
    },
    {
      date: "2026-02-25",
      dateLabel: "2/25",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 3 Matches Made",
    },
    {
      date: "2025-10-22",
      dateLabel: "10/22",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 4 Matches Made",
    },
    {
      date: "2025-10-18",
      dateLabel: "10/18",
      title: "Speed Dating Brunch @ MáLà Greenpoint",
      stats: "40 Singles, 3 Matches Made",
    },
    {
      date: "2025-10-04",
      dateLabel: "10/4",
      title: "Speed Dating Dinner @ MáLà Greenpoint",
      stats: "40 Singles, 3 Matches Made",
    },
    {
      date: "2025-09-20",
      dateLabel: "9/20",
      title: "Speed Dating Dinner @ MáLà Greenpoint",
      stats: "40 Singles, 2 Matches Made",
    },
    {
      date: "2025-09-11",
      dateLabel: "9/11",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 3 Matches Made",
    },
    {
      date: "2025-08-28",
      dateLabel: "8/28",
      title: "Speed Dating Dinner @ MáLà East Village",
      stats: "28 Singles, 2 Matches Made",
    },
    {
      date: "2025-08-21",
      dateLabel: "8/21",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 2 Matches Made",
    },
    {
      date: "2025-07-24",
      dateLabel: "7/24",
      title: "Speed Dating Dinner @ MáLà East Village",
      stats: "36 Singles, 4 Matches Made",
    },
    {
      date: "2025-07-17",
      dateLabel: "7/17",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 5 Matches Made",
    },
    {
      date: "2025-06-28",
      dateLabel: "6/28",
      title: "Speed Dating Dinner @ MáLà Greenpoint",
      stats: "40 Singles, 3 Matches Made",
    },
    {
      date: "2025-06-26",
      dateLabel: "6/26",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 3 Matches Made",
    },
    {
      date: "2025-05-17",
      dateLabel: "5/17",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 2 Matches Made",
    },
    {
      date: "2025-05-15",
      dateLabel: "5/15",
      title: "Speed Dating Dinner @ MáLà Greenpoint",
      stats: "40 Singles, 5 Matches Made",
    },
    {
      date: "2025-04-17",
      dateLabel: "4/17",
      title: "Speed Dating Dinner @ MáLà Midtown",
      stats: "32 Singles, 3 Matches Made",
    },
  ],
};
